### ISSUE TITLE
TypeError: 'canPlayType' called on an object that does not implement interface HTMLMediaElemen

### ISSUE THREAD

**Issue by gonzalo1059** [AlexxIT/WebRTC#586]
After upgrading to v3.4.0 video doesn't play, it keeps "loading..." and I get the following on the integration log:

2023-10-19 11:32:32.760 ERROR (MainThread) [frontend.js.latest.202310050] Uncaught error from Firefox 118.0 on Windows 10
TypeError: 'canPlayType' called on an object that does not implement interface HTMLMediaElement.
codecs/< (/webrtc/video-rtc.js:188:41)
codecs (/webrtc/video-rtc.js:188:14)
onmp4 (/webrtc/video-rtc.js:650:45)
onopen (/webrtc/video-rtc.js:355:18)
onopen (/webrtc/webrtc-camera.js:168:30)
onconnect/< (/webrtc/video-rtc.js:298:53)

**Comment by gonzalo1059** [comment]
After upgrading to v3.4.0 video doesn't play and I get the following on the integration log:

2023-10-19 11:32:32.760 ERROR (MainThread) [frontend.js.latest.202310050] Uncaught error from Firefox 118.0 on Windows 10
TypeError: 'canPlayType' called on an object that does not implement interface HTMLMediaElement.
codecs/< (/webrtc/video-rtc.js:188:41)
codecs (/webrtc/video-rtc.js:188:14)
onmp4 (/webrtc/video-rtc.js:650:45)
onopen (/webrtc/video-rtc.js:355:18)
onopen (/webrtc/webrtc-camera.js:168:30)
onconnect/< (/webrtc/video-rtc.js:298:53)

**Comment by gonzalo1059** [comment]
I've found that "mode: mp4" is no longer supported.

It works fine by removing mp4

**Comment by gonzalo1059** [comment]
> I've found that "mode: mp4" is no longer supported.
> 
> It works fine by removing mp4

**Comment by AlexxIT** [comment]
Mode supported, problem should be fixed
