### ISSUE TITLE
Uncaught TypeError: this.ondata is not a function

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/WebRTC#397]
This keeps appearing in my HA logs:

```
2023-01-23 13:08:39.594 ERROR (MainThread) [frontend.js.latest.202301100] https://<ha>/webrtc/video-rtc.js:313:22 Uncaught TypeError: this.ondata is not a function
```

And I wonder if there is something that can be done to fix it.

**Comment by bigmoby** [comment]
The same error as above and if this could help you I have also another error message in the previous WebRTC version not shown:
```
2023-01-24 19:47:25.937 ERROR (MainThread) [frontend.js.latest.202301100] https://<ha>/webrtc/video-rtc.js:389:27 Uncaught NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="avc1.000001"') is unsupported.
2023-01-24 19:47:25.957 ERROR (MainThread) [frontend.js.latest.202301100] https://<ha>/webrtc/video-rtc.js:313:22 Uncaught TypeError: this.ondata is not a function
```

The rtsp camera url is: `rtsp://[USER]:[PWD]@192.168.1.13:554/11`

Thanks a lot for your help,
Fabio

**Comment by PeteDenmark** [comment]
Same issue here. I am on a fresh install og the newest Home assistant OS on an intel NUC5i5:

2023-01-23 13:08:39.594 ERROR (MainThread) [frontend.js.latest.202301100] https://<ha>/webrtc/video-rtc.js:313:22 Uncaught TypeError: this.ondata is not a function

Thankful for any help you might provide :)

**Comment by felipecrs** [comment]
As mentioned here (https://github.com/AlexxIT/WebRTC/issues/419#issuecomment-1426889797) this issue no longer occurs for me with go2rtc 1.1.2, at least not my cameras.

If this issue is happening for others even after upgrading go2rtc to 1.1.2, I would suggest opening a separate issue with details about your camera.
