### ISSUE TITLE
Chrome v145 seems to have broken autoplay with ui: true?

### ISSUE THREAD

**Issue by furkandeger** [AlexxIT/WebRTC#936]
WebRTC Integration ver: 3.6.1
Installation method
Home Assistant OS
Core
2026.3.1
Supervisor
2026.02.3
Operating System
17.1
Frontend
20260304.0

Ever since updating Chrome to 145, the autoplay seems to have broken. The stream doesn't start at all with the ui: true, and if that's set to false the video doesn't start playing automatically and you have to press the play button (on Chrome mobile as well).

Companion app seems to work fine, so does Microsoft Edge. This is what the logs from HAOS shows: 

Logger: frontend.js.modern.202603040
Source: components/system_log/__init__.py:331
First occurred: 11:42:45 (470 occurrences)
Last logged: 11:57:37

Uncaught error from Chrome 145.0.0.0 on Windows 10 TypeError: this.play is not a function WebRTCCamera.onpcvideo (/webrtc/video-rtc.js:615:22) WebRTCCamera.onpcvideo (/webrtc/webrtc-camera.js:204:15) video2.addEventListener.once (/webrtc/video-rtc.js:529:66)
Uncaught error from Chrome 145.0.0.0 on Windows 10 TypeError: this.play is not a function WebRTCCamera.connectedCallback (/webrtc/video-rtc.js:231:18) apply (node_modules/@webcomponents/scoped-custom-element-registry/src/scoped-custom-element-registry.ts:424:39) insertBefore (node_modules/lit-html/src/lit-html.ts:1507:52) O (node_modules/lit-html/src/lit-html.ts:1551:35) T (node_modules/lit-html/src/lit-html.ts:1497:11) _$AI (node_modules/lit-html/src/lit-html.ts:1287:15) p (node_modules/lit-html/src/lit-html.ts:1641:50) $ (node_modules/lit-html/src/lit-html.ts:1480:11) _$AI (node_modules/lit-html/src/directive-helpers.ts:197:7) d (node_modules/lit-html/src/directives/repeat.ts:342:10)
Uncaught error from Chrome 145.0.0.0 on Windows 10 TypeError: this.play is not a function HTMLDivElement.<anonymous> (/webrtc/webrtc-camera.js:548:22)
Uncaught error from Chrome 145.0.0.0 on Windows 10 TypeError: this.play is not a function WebRTCCamera.connectedCallback (/webrtc/video-rtc.js:231:18) /webrtc/video-rtc.js:305:30 IntersectionObserver.threshold (/webrtc/video-rtc.js:301:25)
Uncaught error from Chrome 145.0.0.0 on Windows 10 TypeError: this.play is not a function WebRTCCamera.connectedCallback (/webrtc/video-rtc.js:231:18) HTMLDocument.<anonymous> (/webrtc/video-rtc.js:294:26)

I previously commented out the play function in the video-rtc.js as suggested to fix the auto mute bug, but reverting that change doesn't fix this (actually re-downloaded the integration just to be on the safe side with no luck).

Edit: Reverting the commented-out play() in the video-rtc.js file and then doing an "Empty Cache and Hard Reload" in Chrome has fixed it (F12 -> Hold refresh).
